### ISSUE TITLE
'-1' degrees is an invalid value

### ISSUE THREAD

**Issue by YougoCodes** [TronFortyTwo/compass#3]
![screenshot20211230_105523848](https://user-images.githubusercontent.com/23282697/147764591-182cddc7-a0b3-4d40-ab96-466f2d07c0d8.png)
![screenshot20211230_105519265](https://user-images.githubusercontent.com/23282697/147764593-7fc9b4f7-145f-444c-871d-a7ff1fd9a056.png)
![screenshot20211230_105521615](https://user-images.githubusercontent.com/23282697/147764594-063db369-ea7b-4cab-a863-b2bee3681499.png)
Device = Pixel 3a
OS = UT 16.04 2021-W51/2 (rc)
App version = 1.0.0 12.29.2021

**Action:**
Start the app. 
Rotate the device to '-1' degrees azimuth

**Expected behavior**
Azimuth indicates '-1' degrees

**actual behavior**
At '-1' degrees the text 'No compass backend found. Check if your device has a working compass sensor' is displayed.
See also attached screenshots.

I'm willing to test, put CLI commands, submit logs.

**Comment by TronFortyTwo** [comment]
Hi! Thank you very much for the report
I think I know the reason of this bug. I'll try to fix it asap
