### ISSUE TITLE
All Azimuth values are in a negative range

### ISSUE THREAD

**Issue by YougoCodes** [TronFortyTwo/compass#4]
Device = Pixel 3a
OS = UT 16.04 2021-W51/2 (rc)
App version = 1.0.0 12.29.2021

Action:
Start the app.
Rotate device to desired positive azimuth value

Expected behavior
Azimuth indicates the corresponding positive value in degrees, counting up clockwise, starting at 1, going around to 359 and rolling over to 0 at N.

actual behavior
First value clockwise is -359, counting upwards, going around clockwise to 0 at N

I'm willing to test, put CLI commands, submit logs.

**Comment by YougoCodes** [comment]
Getting the azimuth to display positive values may also solve issue 3

**Comment by TronFortyTwo** [comment]
Thank you for this report!
It's another side effect of a lazy implementation I did (it also causes #3) in the code.
I'll try to fix this too asap!
